apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: sudheerjazurevotingapp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sudheerjazurevotingapp 
    spec:
      containers:
        - name: sudheerjazurevotingapp 
          image: azurevoting.azurecr.io/sudheerjazurevotingapp
          ports:
          - containerPort: 80